require: rubocop-bridgetown

inherit_gem:
  rubocop-bridgetown: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.7

  Exclude:
    - .gitignore
    - .rspec
    - .rubocop.yml
    - .travis.yml

    - Rakefile
    - "*.gemspec"
    - Gemfile.lock
    - History.markdown
    - LICENSE.txt
    - README.md

    - script/**/*
    - vendor/**/*
    - spec/**/*

